status = ["Build mathlib", "Lint mathlib", "Run tests and docs"]
use_squash_merge = true
timeout_sec = 21600
block_labels = ["not-ready-to-merge", "WIP", "changes-requested", "blocked-by-other-PR"]
delete_merged_branches = true
cut_body_after = "---"
